actions:
  - create
  - update

createM3u:
  entrypoint: init.sh
  scripts:
    - 1_download_yaml.sh
    - 2_create_m3u.sh
    - 3_upload.sh
  cleanup: cleanup.sh
  notify:
    at_start: false
    at_complete: false
    email:
      only_on_failure: false
      list:
        - iptv@bestfabrik.de
    slack:
      only_on_failure: true
      webhook: https://hooks.slack.com/services/xxx...

createYaml:
  entrypoint: init.sh
  scripts:
    - 1_download.sh
    - 2_create_channel_files.sh
    - 3_combine.sh
  cleanup: cleanup.sh
  notify:
    at_start: false
    at_complete: false
    email:
      only_on_failure: false
      list:
        - iptv@bestfabrik.de
    slack:
      only_on_failure: true
      webhook: https://hooks.slack.com/services/xxx...
