actions:
  - create_hls
  - update_hls

create_hls:
  entrypoint: init.sh
  scripts:
    - 1_generate.sh
    - 99_upload.sh
  cleanup: cleanup.sh
  notify:
    at_start: true
    at_complete: true
    email:
      only_on_failure: true
      list:
        - iptv@bestfabrik.de
    slack:
      only_on_failure: true
      webhook: https://hooks.slack.com/services/xxx...

update_hls:
  entrypoint: init.sh
  scripts:
    - 1_download.sh
    - 2_euronews.sh
    - 3_natgeo.sh
    - 4_spektrum_home.sh
    - 5_izaura.sh
    - 6_spektrum.sh
    - 7_natgeo_wild.sh
    - 8_life_tv.sh
    - 9_duna.sh
    - 10_duna_world.sh
    - 11_tv2.sh
    - 12_mozi_plusz.sh
    - 13_moziverzum.sh
    - 14_paramount.sh
    - 15_prime.sh
    - 16_rtl_spike.sh
    - 17_super_tv2.sh
    - 99_upload.sh
  cleanup: cleanup.sh
  notify:
    at_start: false
    at_complete: false
    email:
      only_on_failure: false
      list:
        - iptv@bestfabrik.de
    slack:
      only_on_failure: true
      webhook: https://hooks.slack.com/services/xxx...
